# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|

        config.vm.box = "lucid64"
        config.vm.box_url = "http://files.vagrantup.com/lucid64.box"

        config.vm.host_name = "emmasocial"
        config.vm.network :hostonly, "192.168.33.42"

        config.vm.customize ["modifyvm", :id, "--cpus", 1]
        config.vm.customize ["modifyvm", :id, "--memory", 256]

        config.vm.share_folder "emmasocial", "./emmasocial", "..", :owner=> 'vagrant', :group=>'vagrant'

        config.vm.forward_port 3306, 3306 # MySQL
        config.vm.forward_port 80, 8080   # Not used
        config.vm.forward_port 8000, 8000 # Django development server
        config.vm.forward_port 6379, 6379 # Redis

        config.vm.provision :puppet, :module_path => "modules" do |puppet|
            puppet.manifests_path = "manifests"
            puppet.manifest_file  = "emmasocial.pp"
        end
end


class DjangoShellCommand < Vagrant::Command::Base
  def execute
    exec 'ssh -t emmasocial "source .virtualenvs/emmasocial/bin/activate; cd emmasocial/src; python manage.py shell"'
  end
end
Vagrant.commands.register(:shell) { DjangoShellCommand }


class DjangoRunserverCommand < Vagrant::Command::Base
  def execute
    exec 'ssh -t emmasocial "source .virtualenvs/emmasocial/bin/activate; cd emmasocial/src; sudo python manage.py runserver 0.0.0.0:80"'
  end
end
Vagrant.commands.register(:runserver) { DjangoRunserverCommand }
