# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|

        config.vm.box = "lucid64"
        config.vm.box_url = "http://files.vagrantup.com/lucid64.box"

        config.vm.host_name = "emmasocial"
        config.vm.network :hostonly, "192.168.33.42"

        config.vm.customize ["modifyvm", :id, "--cpus", 1]
        config.vm.customize ["modifyvm", :id, "--memory", 256]

        config.vm.share_folder "emmasocial", "./emmasocial", "..", :owner=> 'vagrant', :group=>'vagrant'

        config.vm.forward_port 80, 8080
        config.vm.forward_port 3306, 3306

        config.vm.provision :puppet, :module_path => "modules" do |puppet|
            puppet.manifests_path = "manifests"
            puppet.manifest_file  = "emmasocial.pp"
        end
end
